### ISSUE TITLE
Problem validating a custom request

### ISSUE THREAD

**Issue by craigwillis85** [urameshibr/lumen-form-request#1]
Hi

I'm trying to use your lib in a Lumen app I'm building. I have followed your install guide and created my own Request class.

This issue is, I get an error:

    Call to undefined method Laravel\\Lumen\\Http\\Redirector::getUrlGenerator()

This happens on `line 166` in:

    vendor/urameshibr/lumen-form-request/src/Requests/FormRequest.php

**Comment by urameshibr** [comment]
Hi friend, could you tell me whats lumen version, please?

**Comment by craigwillis85** [comment]
5.4 and probably 5.3 as well

**Comment by urameshibr** [comment]
Can you help me to reproduce the error? Show me what you are doing on the code, please.
I'm testing and is working fine.

**Comment by BogdanHossu** [comment]
I have the same problem, what I did was to create a simple request, add some rules and authorize true. In my controller I have MyRequest $request and when trying to use the $request I get the above error.

**Comment by BogdanHossu** [comment]
I did fix the problem, ill make PR on your repo.
