### ISSUE TITLE
Method Validate doesnot existed

### ISSUE THREAD

**Issue by ahmad-sa3d** [urameshibr/lumen-form-request#3]
Hello, urameshibr

i'm using your library, on lumen 5.6 i got  an error that validation method doesnot exists

i saw the code and found that you are calling non existing method in service provider

this is the fix is the service provider, replace validate() with validateResolved()

public function boot()
    {
        $this->app->afterResolving(ValidatesWhenResolved::class, function ($resolved) {
            $resolved->validateResolved();
        });
        $this->app->resolving(FormRequest::class, function ($request, $app) {
            $this->initializeRequest($request, $app['request']);
            $request->setContainer($app)->setRedirector($app->make(Redirector::class));
        });
    }

**Comment by urameshibr** [comment]
Hello, @ahmad-sa3d , regards, could you make a Pull Request for this fix?
Thanks, cya.
